### ISSUE TITLE
יכול להוסיף לנו את התרגילים ? המרצה שלנו לא נתן תרגילים של מימוש , אני ממש אבוד :(

### ISSUE THREAD

**Issue by dolev146** [ZviMints/DataStructures_2020S#1]
DataStructures_2020S/תרגול 4 עצים ועץ חיפוש בינארי/

בתרגול 4 של עצים
מופיע הקוד שלך

של הפיתרונות של אליזבט 
של הפתרונות כולל תשובות לראיונות עבודה

אבל לא מוצא את השאלות עצמן 

צבי ימלך
תודה רבה
על הזמן וההשקעה 

אם יש לך את זה בשלוף כמה שיותר מהר
שנוכל לריץ תרגילים למבחן

![4](https://user-images.githubusercontent.com/62290677/130126271-f34be792-47cb-4ece-b19a-30098a07954a.JPG)

**Comment by ZviMints** [comment]
@dolev146 

אתה יכול להסתכל בתרגול עצמו:
https://github.com/ZviMints/DataStructures_2020S/blob/master/%D7%AA%D7%A8%D7%92%D7%95%D7%9C%204%20%D7%A2%D7%A6%D7%99%D7%9D%20%D7%95%D7%A2%D7%A5%20%D7%97%D7%99%D7%A4%D7%95%D7%A9%20%D7%91%D7%99%D7%A0%D7%90%D7%A8%D7%99/%D7%AA%D7%A8%D7%92%D7%95%D7%9C%204%20-%20%D7%A2%D7%A6%D7%99%D7%9D.pdf

ולמצוא את הפתרון לשאלה לפי המספר, לדוגמא שאלה מספר 3
![image](https://user-images.githubusercontent.com/43406781/130430602-4bc25c69-2845-422c-9817-fd48e281e00b.png)

אז הפתרון זה ב `BST_AfterQuestions.java`
![image](https://user-images.githubusercontent.com/43406781/130430819-e079e985-fb4d-4804-862f-89742f94ff12.png)

**Comment by dolev146** [comment]
קלטתי אותך תודה !

אני יסגור את ה issue 
אחרי שאני יעשה את הקובץ הזה ידנית ככה שיהיה לאחרים
